# 1.2. Elements of Linear Algebra
_________________________________
### Key Concepts:
* Orthogonality
* Gram-Schmidt Process
* Eigenvalues and Eigenvectors

In [1]:
import numpy as np
from IPython.core.display import Image

In [2]:
def generate_random_matrix(size: int = 3):
    """
    Generates Random Square Matrix of given Size with Integers (0-99)
    """
    return np.random.randint(0, 100, [size, size])

In [3]:
matrix_size = 3

# Generate a random 3x3 Matrix A
A = generate_random_matrix(matrix_size)
print("Random 3x3 Matrix A:\n", A)

# Generate another random matrix B
B = generate_random_matrix(matrix_size)
print("Random 3x3 Matrix B:\n", B)

Random 3x3 Matrix A:
 [[93 45 61]
 [30 61  3]
 [62 54 34]]
Random 3x3 Matrix B:
 [[21 87 87]
 [44 83 74]
 [56 14 50]]


## Projection

${\displaystyle \operatorname {proj} _{\mathbf {u} }(\mathbf {v} )={\frac {\langle \mathbf {u} ,\mathbf {v} \rangle }{\langle \mathbf {u} ,\mathbf {u} \rangle }}{\mathbf {u} }}$


In [4]:
def project(u, v):
    """
    Project vector u onto v
    :param u: Vector u
    :param v: Vector v
    :return:
    """
    return np.multiply((np.dot(u, v) / np.dot(u, u)), u)

In [5]:
# Project the first col of A onto first col of B
proj_A_B = project(A[:, 0], B[:, 0])
print("A1 Projected onto B1")
print(proj_A_B)

A1 Projected onto B1
[46.83678041 15.10863884 31.22452027]


## Gram-Schmidt Process


In [6]:
Image(url= "https://wikimedia.org/api/rest_v1/media/math/render/svg/c14bc18275503c8b2593498757740976cf0e078a", height=250)

In [7]:
def gram_schmidt(u, v, k):
    """
    Gram Schmidt Process for step k
    :param u: First set of vectors
    :param v: Second set of vectors
    :param k: Step
    :return e: Orthonormal vector
    """
    # Index starts on 0 not 1 in python
    k = k-1
    v_k = v[:, k]

    # Calculate projection matrices
    proj_sum = np.zeros(v_k.shape)
    for j in range(k):
        # Project u_j onto v_k
        proj = project(u[:, j], v_k)

        # Update the projections sum
        proj_sum += proj

    return v_k - proj_sum

In [8]:
# Project A onto B
for i in range(1, matrix_size+1):
    gs_ab_k = gram_schmidt(A, B, i)
    print(f"Gram-Schmidt k={i}\n", gs_ab_k)
    print()

Gram-Schmidt k=1
 [21. 44. 56.]

Gram-Schmidt k=2
 [  7.49899201  57.35451355 -39.00067199]

Gram-Schmidt k=3
 [-63.94131484 -34.41355901 -81.46291612]

