# 1.2. Elements of Linear Algebra
_________________________________
### Key Concepts:
* Orthogonality
* Gram-Schmidt Process
* Eigenvalues and Eigenvectors

In [1]:
import numpy as np
from IPython.core.display import Image

#### Helper Functions

In [2]:
def generate_random_matrix(size: int = 3):
    """
    Generates Random Square Matrix of given Size with Integers (0-99)
    """
    return np.random.randint(0, 100, [size, size])

### Global Variables

In [3]:
matrix_size = 3

# Generate a random 3x3 Matrix A
A = generate_random_matrix(matrix_size)
print("Random 3x3 Matrix A:\n", A)

# Generate another random matrix B
B = generate_random_matrix(matrix_size)
print("Random 3x3 Matrix B:\n", B)

Random 3x3 Matrix A:
 [[95  0 97]
 [19 36 22]
 [65 87  0]]
Random 3x3 Matrix B:
 [[47 22 74]
 [32 65 15]
 [44 97 83]]


## Projection

${\displaystyle \operatorname {proj} _{\mathbf {u} }(\mathbf {v} )={\frac {\langle \mathbf {u} ,\mathbf {v} \rangle }{\langle \mathbf {u} ,\mathbf {u} \rangle }}{\mathbf {u} }}$


In [4]:
def project(u, v):
    """
    Project vector u onto v
    :param u: Vector u
    :param v: Vector v
    :return:
    """
    return np.multiply((np.dot(u, v) / np.dot(u, u)), u)

In [5]:
# Project the first col of A onto first col of B
proj_A_B = project(A[:, 0], B[:, 0])
print("A1 Projected onto B1")
print(proj_A_B)

A1 Projected onto B1
[55.36955404 11.07391081 37.88443171]


## Gram-Schmidt Process


In [6]:
Image(url= "https://wikimedia.org/api/rest_v1/media/math/render/svg/c14bc18275503c8b2593498757740976cf0e078a", height=175)

In [7]:
def gram_schmidt(u, v, k):
    """
    Gram-Schmidt Process for step k
    :param u: First set of vectors
    :param v: Second set of vectors
    :param k: Step
    :return e: Orthonormal vector
    """
    # Index starts at 0 (not 1) in python
    k = k-1

    # Get v_k
    v_k = v[:, k]

    # Calculate projection matrices
    proj_sum = np.zeros(v_k.shape)

    # Iterate from first to second-to-last element
    for j in range(0, k):

        # Project u_j onto v_k
        proj_sum += project(u[:, j], v_k)

    # Calculate the new vector
    u_k = (v_k - proj_sum)

    # Normalize
    e_k = (u_k / np.linalg.norm(u_k))

    return e_k

In [8]:
def gram_schmidt_matrix(A):
    """
    Find the Gram-Schmidt of a Matrix
    """

    # Set A to float type
    A = A.astype('float64')

    # Copy A. First column remains the same
    U = np.copy(A.astype('float64'))

    # Copy A. First column is the same but normalized
    E = np.zeros(A.shape)
    E[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0])

    # Iterate through each column
    for k in range(1, U.shape[1]):

        u_k = A[:, k]

        # Iterate through each column to the left of k
        for j in range(k):
            u_k -= project(U[:, j], A[:, k])

        # Update U
        U[:, k] = u_k

        # Update E
        E[:, k] = U[:, k] / np.linalg.norm(U[:, k])

    return E

In [9]:
# Calculate the Gram-Schmidt of A
gs_A = gram_schmidt_matrix(A)

print("Gram-Schmidt Matrix of A:")
print(gs_A)

Gram-Schmidt Matrix of A:
[[ 0.81428904 -0.57538581  0.07658021]
 [ 0.16285781  0.35309688  0.92130339]
 [ 0.55714513  0.73773556 -0.38122899]]
