# 1.3. Linear Regression
_________________________________
### Key Concepts:
* QR Decomposition
* Least Squares
* Linear Regression

In [1]:
import numpy as np
from IPython.core.display import Image

### Helper Functions

In [2]:
def generate_random_matrix(size: int = 3):
    """
    Generates Random Square Matrix of given Size with Integers (0-99)
    """
    return np.random.randint(0, 100, [size, size])

In [3]:
def project(u, a):
    """
    Project vector u onto a
    """
    return (np.dot(u, a) / np.dot(u, u)) * u

In [4]:
def gram_schmidt_matrix(A):
    """
    Find the Gram-Schmidt of a Matrix
    """

    # Set A to float type
    A = A.astype('float64')

    # Copy A. First column remains the same
    U = np.copy(A.astype('float64'))

    # Copy A. First column is the same but normalized
    E = np.zeros(A.shape)
    E[:, 0] = A[:, 0] / np.linalg.norm(A[:, 0])

    # Iterate through each column
    for k in range(1, U.shape[1]):

        u_k = A[:, k]

        # Iterate through each column to the left of k
        for j in range(k):
            u_k -= project(U[:, j], A[:, k])

        # Update U
        U[:, k] = u_k

        # Update E
        E[:, k] = U[:, k] / np.linalg.norm(U[:, k])

    return E

### Global Variables

In [5]:
matrix_size = 3

# Generate a random 3x3 Matrix A
A = generate_random_matrix(matrix_size)
print("Random 3x3 Matrix A:\n", A)

# Generate another random matrix B
B = generate_random_matrix(matrix_size)
print("Random 3x3 Matrix B:\n", B)

Random 3x3 Matrix A:
 [[60 67 10]
 [93 66 71]
 [89 74 77]]
Random 3x3 Matrix B:
 [[20  4 72]
 [18 30 49]
 [65 44 80]]


## QR Decomposition

A square matrix $A$ is decomposed as
$A=QR$
where $Q$ is an orthogonal matrix (i.e. $Q ^T = Q ^{-1}$)
and $R$ is an upper/right triangular matrix

Formulas:
$Q = [e _1 ... e _k ]$
$R = Q ^T A$

In [6]:
def QR(A):
    """
    QR Decomposition of A
    :param A: Square Matrix A
    :return: (Q, R)
    """

    # Calculate Q
    Q = gram_schmidt_matrix(A)

    # Calculate R
    R = np.zeros(A.shape)
    for row in range(A.shape[0]):
        for col in range(row, A.shape[0]):
            R[row, col] = np.dot(A[:, col], Q[:, row])

    return Q, R

In [7]:
Q_A, R_A = QR(A)

print(f"QR Decomposition of A:\n{A}\n")
print(f"Q:\n{Q_A}\n")
print(f"R:\n{R_A}\n")

QR Decomposition of A:
[[60 67 10]
 [93 66 71]
 [89 74 77]]

Q:
[[ 0.42247236  0.83778405 -0.34588291]
 [ 0.65483216 -0.54597185 -0.52259888]
 [ 0.62666733  0.00571167  0.77926595]]

R:
[[142.02112519 117.8979534   98.97119165]
 [  0.          20.52005319 -29.94636204]
 [  0.           0.          19.4401292 ]]



#### Verify Q is Orthonormal
$Q \cdot Q ^T = I$

In [8]:
# Calculate QQt
QQt_A = np.dot(Q_A, np.transpose(Q_A))
# Round to 5 decimals
QQt_A = np.round(QQt_A, 5)

print(f"QQt:\n {QQt_A} \n")

# Check if QQt is an Identity Matrix
QQt_is_I = np.allclose(QQt_A, np.eye(A.shape[0]))
print(f"QQt {'IS' if QQt_is_I else 'IS NOT'} an Identity Matrix")

QQt:
 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]] 

QQt IS an Identity Matrix


#### Verify $A=QR$

In [9]:
# Calculate A=QR
AQR = np.dot(Q_A, R_A)
print(f"A:\n {A} \n")
print(f"QR:\n {AQR} \n")

# Check if QR = A
QR_is_A = np.allclose(AQR, A)
print(f"QR {'==' if QR_is_A else '!='} A")

A:
 [[60 67 10]
 [93 66 71]
 [89 74 77]] 

QR:
 [[60. 67. 10.]
 [93. 66. 71.]
 [89. 74. 77.]] 

QR == A
